language: php
php:
    - '7.0'
    - '7.1'
install:  
    composer install
script:
  -  ./vendor/bin/codecept run unit
  -  ./vendor/bin/phpcs --standard=PSR1,PSR2 ./src
  -  ./vendor/bin/phpmd ./src text codesize,unusedcode,naming,cleancode,design
  -  ./vendor/bin/phpcpd ./src
  